name: hexlet-ci-app_checkout
run-name: ${{ github.actor }} is testing out 🚀
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check out setup
        run: make setup
      - name: Check out test
        run: make test
      - name: Check out lint
        run: make lint
